version: '3.3'
services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
      ports:
        - 9200:9200
        - 9300:9300
      networks:
        - network
      healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail elasticsearch:9200/_cluster/health || exit 1"]
        interval: 30s
        timeout: 30s

    kibana:
      image: docker.elastic.co/kibana/kibana:7.13.4
      container_name: kibana
      environment:
          - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      ports:
          - 5601:5601
      networks:
          - network
      depends_on:
        elasticsearch:
          condition: service_healthy

    titanicapi:
      build:
        context: .
        dockerfile: ./docker/api/Dockerfile
      container_name: titanic_api
      ports:
        - 8000:8000
      healthcheck:
        test: ["CMD", "wget", "http://titanicapi:8000/healthcheck"]
        interval: 1s
      depends_on:
        elasticsearch:
          condition: service_healthy
  
    producer:
      build:
        context: .
        dockerfile: ./docker/producer/Dockerfile
      container_name: producer
      depends_on:
        titanicapi:
          condition: service_healthy
        
networks:
    network: 
        driver: bridge
