version: '3.3'
services:
    titanic_api:
      build: .
      container_name: titanic_api
      ports:
        - 8000:8000
      depends_on:
        - elasticsearch
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
      ports:
        - 9200:9200
        - 9300:9300
      networks:
        - network
    kibana:
        image: docker.elastic.co/kibana/kibana:7.13.4
        container_name: kibana
        environment:
            - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
        ports:
            - 5601:5601
        networks:
            - network
networks:
    network: 
        driver: bridge
