version: '3.3'
services:
    toy_model:
      build: .
      ports:
        - 8000:8000
      networks:
        - toy_model
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
      ports:
        - 9200:9200
        - 9300:9300
      networks:
        - toy_model
    kibana:
        image: docker.elastic.co/kibana/kibana:7.13.4
        container_name: kibana
        environment:
            - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
        ports:
            - 5601:5601
        networks:
            - toy_model
networks:
    toy_model: 
        driver: bridge
