version: 2 # use CircleCI 2.0

orbs:
    docker: circleci/docker@1.0.1

jobs:
    prepare-dependencies:
      docker:
        - image: circleci/python:3.8
        - run:
          command: |
            sudo pip install pipenv
            pipenv install         

    tests:
      docker: 
        - image: circleci/python:3.8
        - run:
          command: |
            pipenv run pytest

workflows:
    version: 2
    build-test:
        jobs:
        - prepare-dependencies
        - tests:
            requires:
              - prepare-dependencies
