version: 2 # use CircleCI 2.0
orbs:
  node: circleci/python:3.8
jobs:
  prepare-dependencies:
    executor: python/default
    steps:
      - checkout
      - run: |
          sudo pip install pipenv
          pipenv install
  tests:
    docker:
      - image: cimg/python:current
    steps:
      - attach_workspace:
        at: .
      - run: |
          pipenv run pytest
workflows:
    version: 2
    build-test:
        jobs:
        - prepare-dependencies
        - tests:
            requires:
              - prepare-dependencies