version: 2.1

orbs:
  docker: circleci/docker@1.6.0  
  python: circleci/python@1.4.0

jobs:
  tests:
    working_directory: ~/toy_model
    docker:
      - image: cimg/python:3.8.0
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt 
      - run:
          name: "Executing the tests"
          command: |  
            pipenv run pytest

  docker-build:
    working_directory: ~/toy_model
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Executing the tests"
          command: |  
            ls  /home/circleci/toy_model
      - docker/build:
          debug: false 
          dockerfile: Dockerfile 
          image: toy_model 
          path: .
          registry: docker.io 
          step-name: Docker Build 
          tag: $CIRCLE_SHA1 

workflows:
    main:
      jobs:
        - tests
        - docker-build:
            requires:
            - tests