version: 2.1

orbs:
  python: circleci/python@1.4.0
  docker: circleci/docker@1.6.0  

jobs:
  docker-build:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/build:
          debug: false 
          dockerfile: Dockerfile 
          image: toy_model 
          lint-dockerfile: true 
          path: . 
          registry: docker.io 
          step-name: Docker Build 
          tag: $CIRCLE_SHA1 
          treat-warnings-as-errors: true 

workflows:
    main:
      jobs:
        - python/test:
            app-dir: ~/toy_model 
            pip-dependency-file: requirements.tx 
            pkg-manager: pip 
            test-tool: pytest 
            version: '3.8' 
        - docker-build:
            requires:
            - python/test