version: 2 # use CircleCI 2.0

jobs:
  prepare-dependencies:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: |
          sudo pip install pipenv
          pipenv install
  tests:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: |
          pipenv run pytest
workflows:
    version: 2
    build-test:
        jobs:
        - prepare-dependencies
        - tests:
            requires:
              - prepare-dependencies