version: 2.1

orbs:
  docker: circleci/docker@1.6.0  
  python: circleci/python@1.4.0

jobs:
  tests:
    working_directory: ~/toy_model
    docker:
      - image: cimg/python:3.8.0
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt 
      - run:
          name: "Executing the tests"
          command: |  
            pipenv run pytest
  docker-build:
    working_directory: ~/toy_model
    docker:
      - image: cimg/base:stable
    steps:
      - run: 
          name: "Building the Docker Image"
          command: |
            docker build -t ericvenarusso/toy_model:$CIRCLE_SHA1 .
workflows:
    main:
      jobs:
        - tests
        - docker-build:
            requires:
            - tests