version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  build:
    docker:
      # replace with your preferred image
      - image: cimg/python:3.8
    steps:
      - python/install-packages:
          app-dir:  ~/toy_model 
          pip-dependency-file: requirements.txt 

workflows:
    main:
      jobs:
        - build
        - python/test:
            test-tool: pytest 