version: 2.1

orbs:  
  python: circleci/python@1.4.0
  docker: circleci/docker@1.6.0

jobs:
  tests:
    working_directory: ~/toy_model
    docker:
      - image: cimg/python:3.8.0
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt 
      - run:
          name: "Executing the tests"
          command: |  
            pipenv run pytest      
  codecov:
    working_directory: ~/toy_model
    docker:
      - image: cimg/python:3.8.0
    steps:
      - checkout
      - run:
          name: "Installing CodeCov" 
          command: |
            sudo pip install codecov
      - run:
          name: "CodeCov Report"
          command: | 
            mkdir test-reports
            coverage report && coverage xml -o test-reports/coverage.xml
      - store_test_results:
          path: test-reports
  docker-build-publish:
    working_directory: ~/toy_model
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Docker Login"
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
      - run:
          name: "Building Docker Image"
          command: |
            docker build -t $DOCKERHUB_USERNAME/toy_model:$CIRCLE_SHA1 .
      - run:
          name: "Pushing Docker Image"
          command: |
            docker push $DOCKERHUB_USERNAME/toy_model:$CIRCLE_SHA1
workflows:
    main:
      jobs:
        - tests
        - codecov
        - docker-build-publish:
            requires:
            - tests
            - codecov