
version: 2.1
orbs:
  python: circleci/python@1.4.0

jobs:
  example-job:
    docker:
      - image: cimg/python:3.8
    steps:
      - python/install-packages:
          app-dir: ~/toy_model 
          pip-dependency-file: requirements.txt 

workflows:
  example-workflow:
    jobs:
      - example-job
      - python/test:
          test-tool: pytest 