version: 2.1

orbs:
  docker: circleci/docker@1.6.0  

jobs:
  tests:
    working_directory: ~/toy_model
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run:
          name: "Installing Dependencies"
          command: |  
            sudo pip install pipenv
            pipenv install
      - run:
          name: "Executing the tests"
          command: |  
            pipenv pytest

  docker-build:
    docker:
      - image: cimg/base:stable
    steps:
      - docker/build:
          debug: false 
          dockerfile: Dockerfile 
          image: toy_model 
          lint-dockerfile: true 
          path: . 
          registry: docker.io 
          step-name: Docker Build 
          tag: $CIRCLE_SHA1 
          treat-warnings-as-errors: true 

workflows:
    main:
      jobs:
        - tests
        - docker-build:
            requires:
            - tests