version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  install-packages:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - python/install-packages:
          app-dir: ~/toy_model 
          pip-dependency-file: requirements.txt 

workflows:
  build-test:
    jobs:
      - install-packages
      - python/test:
          requires: 
            - install-packages
          app-dir: ~/toy_model 
          test-tool: pytest 
          version: '3.8' 