version: 2.1

orbs:  
  python: circleci/python@1.4.0
  docker: circleci/docker@1.6.0

jobs:
  tests:
    working_directory: ~/toy_model
    docker:
      - image: cimg/python:3.8.0
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt 
      - run:
          name: "Executing the tests"
          command: |  
            pipenv run pytest
  docker-build:
    working_directory: ~/toy_model
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker build -t toy_model:$CIRCLE_SHA1 .
  docker-publish:
    working_directory: ~/toy_model
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p $DOCKERHUB_PASS 
            docker push toy_model:$CIRCLE_SHA1

workflows:
    main:
      jobs:
        - tests
        - docker-build:
            requires:
            - tests
        -  docker-publish:
            requires:
            - docker-build